module CsvReader

  # Contains numbers for CSV fields
  module Fields
    JLIVES_ID = 0
    TITLE = 1
    LAST_NAME = 2
    FIRST_NAME_ABBREV = 3
    FULL_FIRST_NAME = 4
    BIRTH_DATE = 5
    PLACE_OF_BIRTH = 6
    ENTRANCE_DATE_1 = 7
    ENTRANCE_DATE_2 = 8
    ENTRANCE_PROVINCE = 9
    ENTRANCE_PROVINCE_2 = 10
    STATUS = 11
    VOW_DATE = 12
    DEATH_DATE = 13
    PLACE_OF_DEATH = 14
    ORDINATION_DATE = 15
    ALT_LAST_NAME = 16
    ADD_LAST_NAME_INFO = 17
    ALT_FIRST_NAME = 18
    ADD_FIRST_NAME_INFO = 19
    ALT_BIRTH_DATE = 20
    ADD_BIRTH_DATE_INFO = 21
    ALT_PLACE_OF_BIRTH = 22
    ADD_PLACE_OF_BIRTH_INFO = 23
    ALT_ENTRANCE_DATE_I1 = 24
    ALT_ENTRANCE_DATE_I1_INFO = 25
    ALT_ENTRANCE_DATE_I2 = 26
    ADD_ENTRANCE_DATE_I2_INFO = 27
    ADD_ENTRANCE_PLACE_INFO_I1 = 28
    ADD_ENTRANCE_PLACE_INFO_I2 = 29
    ALT_FINAL_VOW_DATE = 30
    ADD_FINAL_VOW_DATE_INFO = 31
    ADD_STATUS_INFO = 32
    ALT_DEATH_DATE = 33
    ADD_DEATH_DATE_INFO = 34
    ALT_PLACE_OF_DEATH = 35
    ADD_PLACE_OF_DEATH_INFO = 36
  end
end
