module CsvReader

  # Contains numbers for CSV fields
  module Fields
    LINKING_ID = 0
    JLIVES_ID = 1
    TITLE = 2
    LAST_NAME = 3
    FIRST_NAME_ABBREV = 4
    FULL_FIRST_NAME = 5
    BIRTH_DATE = 6
    PLACE_OF_BIRTH = 7
    ENTRANCE_DATE_1 = 8
    ENTRANCE_DATE_2 = 9
    ENTRANCE_PROVINCE = 10
    ENTRANCE_PROVINCE_2 = 11
    STATUS = 12
    VOW_DATE = 13
    DEATH_DATE = 14
    PLACE_OF_DEATH = 15
    ORDINATION_DATE = 16
    ALT_LAST_NAME = 17
    ADD_LAST_NAME_INFO = 18
    ALT_FIRST_NAME = 19
    ADD_FIRST_NAME_INFO = 20
    ALT_BIRTH_DATE = 21
    ADD_BIRTH_DATE_INFO = 22
    ALT_PLACE_OF_BIRTH = 23
    ADD_PLACE_OF_BIRTH_INFO = 24
    ALT_ENTRANCE_DATE_I1 = 25
    ADD_ENTRANCE_DATE_I1_INFO = 26
    ALT_ENTRANCE_DATE_I2 = 27
    ADD_ENTRANCE_DATE_I2_INFO = 28
    ADD_ENTRANCE_PLACE_INFO_I1 = 29
    ADD_ENTRANCE_PLACE_INFO_I2 = 30
    ALT_FINAL_VOW_DATE = 31
    ADD_FINAL_VOW_DATE_INFO = 32
    ADD_STATUS_INFO = 33
    ALT_DEATH_DATE = 34
    ADD_DEATH_DATE_INFO = 35
    ALT_PLACE_OF_DEATH = 36
    ADD_PLACE_OF_DEATH_INFO = 37
  end
end
